nyaga = {
  marta : {
      ricikan : "bonangPan",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  panca : {
      ricikan : "peking",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  dana : {
      ricikan : "saronA",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  harja : {
      ricikan : "gong",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  tana : {
      ricikan : "gérongan",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  yana : {
      ricikan : "demung",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  wanda : {
      ricikan : "kempyang",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  rana : {
      ricikan : "gérongan",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  sabda : {
      ricikan : "kenong",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "male"
  },
  darti : {
      ricikan : "kendhang",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "female"
  },
  parsih : {
      ricikan : "gendèr",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "female"
  },
  lastri : {
      ricikan : "bonangBar",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "female"
  },
  ratri : {
      ricikan : "slenthem",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "female"
  },
  warsi : {
      ricikan : "kethuk",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "female"
  },
  narti : {
      ricikan : "saronB",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "female"
  },
  rani : {
      ricikan : "sindhénan",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "female"
  },
  tatik : {
      ricikan : "kempul",
      amp : 1,
      ampVar: 1,
      timingVar : 1,
      attack : 1,
      decay : 1,
      lag : 1,
      empathy : 1,
      confidence : 1,
      fanciness : 1,
      sex : "female"
  }
}
